### ISSUE TITLE
I dont' see anything relating to IAC in the aiac code...

### ISSUE THREAD

**Issue by bdmorin** [gofireflyio/aiac#124]
This appears to be a frontend for models with a little spice of formatting. Is there something I'm missing? I asked it to quote shakespeare and we had a lovely chat about Henry Vth.

I'm just not sure what makes this an IAC tool.

**Comment by ido50** [comment]
Yes, the only IaC related piece of code—and even that may be considered a stretch—is the prompt formatting in main.go.
The library itself cares nothing about IaC and can be used as a generic frontend.

Originally, we were intending on also validating the output (e.g. ensuring a generated Terraform template is syntactically correct), but that would have required adding a lot of dependencies to the code for a relatively small benefit. Eventually we decided to implement that logic in our own system that uses aiac for a small set of very specific IaC products.

We're always toying with ideas for doing more IaC related activities in aiac, but we haven't landed on anything that is sufficiently "generic" enough to provide benefit for many kinds of IaC products/needs.

If you have any suggestions, we'll be happy to hear them. I am closing this issue because, well, I don't think it's an issue.

**Comment by francardoso93** [comment]
I think the question is: what makes this tool more interesting than asking GH copilot to write the code?

**Comment by basher83** [comment]
> I think the question is: what makes this tool more interesting than asking GH copilot to write the code?

I stumbled upon this repo today and was intrigued at first. After looking at it I had the exact same question. Which led me to the issues section .... I shall just move on
